### ISSUE TITLE
初始化登陆用户后，无法登陆问题

### ISSUE THREAD

**Issue by Linkding** [lifei825/devops-flask-vue#3]
在解决了导入初始化用户的数据库问题后，尝试登陆，报错如图：
![qq 20171206175947](https://user-images.githubusercontent.com/13794365/33655864-45393010-daaf-11e7-82c6-3ae551c38c6d.png)
在服务器内使用curl命令也做了测试：
```
[root@localhost devops-flask-vue]# curl -i -X POST -H "Content-Type: application/json" -d '{"username":"lifei","password":"123"}' http://127.0.0.1:8082/api/v1/login
HTTP/1.0 451 UNAVAILABLE FOR LEGAL REASONS
Content-Type: application/json
Content-Length: 507
Access-Control-Allow-Origin: *
Server: Werkzeug/0.12.2 Python/3.5.1
Date: Wed, 06 Dec 2017 11:51:48 GMT

{
    "state": "Invalid credentials",
    "result": {
        "permission": {
            "1": [
                "view",
                "View"
            ],
            "2": [
                "editor",
                "Editor"
            ],
            "4": [
                "op",
                "Operator"
            ],
            "255": [
                "admin",
                "administrator"
            ]
        },
        "username": null,
        "exp": null,
        "token": null
    }
}
```
从curl结果看，view.py的对应`Auth`路由里只有permission是正常工作的，username，exp，token都没有返回数据，所以导致登陆失败。

**Comment by lifei825** [comment]
最近刚换了新工作 没精力更新了... 
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'email=lifei&password=123' 'http://127.0.0.1:8082/api/v1/login'

api文档自动生成curl命令  http://127.0.0.1:8082/apidocs/#!/LOGIN/post_api_v1_login
----------------------
页面登录看下密码是否正确及参考下面

修改这个配置文件./vue-init/src/api/config.js

// vue编译后用flask访问 （生产环境）
export const baseUrl = '';

//npm run dev 访问 （开发测试）
export const baseUrl = 'http://127.0.0.1:8082';

**Comment by Linkding** [comment]
@lifei825 我们部署在了一台有公网ip的机器上，前端vue启动我们修改成`dev-server.js`中的
```
var uri = 'http://0.0.0.0:' + port
```
所以我们前端启动后，我们是在外网访问的打开的地址是：http://103.227.130.62:8080

是不是因为后端，也需要启动在一个外网可以访问的地址才能访问呢？？

目前我们后端flask启动时监听在内网的，如下：
```
 python manage.py runserver -h 127.0.0.1 -p 8082 --debug
```
从而导致，前端链接不到后端的api呢?

还是说，后端的请求会在服务器内部去请求127.0.0.1:8082，去交互数据？

**Comment by lifei825** [comment]
要是正式环境启动 编辑./vue-init/src/api/config.js修改为export const baseUrl = ''; 编译vue 生成静态目录dist，直接启动flask就可以了  不用启动再单独启动vue了

要是开发测试 编辑./vue-init/src/api/config.js修改为export const baseUrl = 'http://ip:端口';同时启动vue和flask，此时用vue的url来访问（flask访问是旧的不变的dist）这样方便开发 不用重复编译vue

**Comment by Linkding** [comment]
@lifei825 好的 谢谢大神，我修改`export const baseUrl = 'http://公网ip:8082';` ,成功登陆了!
vue编译这个部分我再学习下，刚起步使用

**Comment by Linkding** [comment]
@lifei825 补问下，如果执行`npm run build`编译，生成静态目录dist后，这个目录需要放到什么位置，比如我启动一个nginx作为web服务能找到这个静态文件。但是交互数据，他们怎么工作？

**Comment by lifei825** [comment]
默认位置就行了（./vue-init/dist）  flask代码里指定了去这个位置找vue的静态资源, 不用nginx，nginx直接代理flask就好了

**Comment by Linkding** [comment]
@lifei825 OK。我将nginx配置文件直接监听flask的8082端口，根目录直接设定到devops-flask-vue目录，
```
 server {
        listen       8082;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   /export/projects/devops-flask-vue/;
            index  index.html index.htm;
        }
```

但是直接打开公网地址：http://103.227.130.62，会直接报404的，没有太明白，这个时候flask是怎么工作的，如何找到index.html？

**Comment by lifei825** [comment]
你可以参考下面的ngx配置
```
cat /etc/nginx/conf.d/nginx_uwsgi.conf
server {
    listen     80;
    server_name  103.227.130.62;
    location / {
        proxy_pass http://127.0.0.1:8082;
    }
    }
```

**Comment by Linkding** [comment]
@lifei825 按以上设置了，打开会报错（你ka可以打开公网地址查看），看了下manger.py的路由是找game.html这个文件，尝试换成index.html，报错一样
![qq 20171207180640](https://user-images.githubusercontent.com/13794365/33709765-66c226b8-db79-11e7-8c1d-8eb51d8074b3.png)

**Comment by lifei825** [comment]
不要用manger.py起  用main.py起

**Comment by Linkding** [comment]
@lifei825 终于正常啦，谢谢大神
